### ISSUE TITLE
./install.sh does not really install

### ISSUE THREAD

**Issue by rhl-bthr** [NUS-SNL/p4-traffictool#14]
`./install.sh` adds an alias to `p4-traffictool.sh` *within the* (downloaded) source code.

Ideally, it should copy the source code and `p4-traffictool.sh` to `/bin`, similar to what a `.deb` package would do.

**Comment by rhl-bthr** [comment]
Also, should `configure` and `install` be merged? (with a `--check-requirements` option that only performs the dependency check)

**Comment by rajkiranjoshi** [comment]
It is a matter of preference. You may copy `p4-traffictool.sh` to `/bin`. But then it is only a high-level script. Rest of the code execution happens in the files. So it becomes weird that a `/bin` executable isn't self-contained. 

At the same time, I am a little uncomfortable with install scripts messing around with my config files like `.bashrc`. 

Do you have a better idea about how we can allow tool invocation from anywhere while avoiding the above issues?

**Comment by rhl-bthr** [comment]
Sorry for the confusion. Rephrasing my original comment - 
Should execution of `./install.sh` move the entire source code to `/usr/share` and the invoking script to `/usr/bin`. (Similar to what a package installed via apt would do)

This will also make it easier to generate and distribute the tool via ppa

**Comment by rajkiranjoshi** [comment]
Okay, this sounds good. Having a ppa for the tool is also a good plan. You can probably add a card/issue to track this feature of ppa packaging for the tool 😃

**Comment by rhl-bthr** [comment]
Done
