### ISSUE TITLE
p4-traffictool cannot generate scapy code

### ISSUE THREAD

**Issue by Xiangpeng-Sun** [NUS-SNL/p4-traffictool#38]
Our team try to introduce p4-traffictool into our p4 traffic test unit. However, when we try to use p4-traffictool to generate scapy code base on our p4 code, the tool says it cannot generate scapy.
![image](https://user-images.githubusercontent.com/34417280/96362280-c84cb380-115e-11eb-882d-0dcac43ad2b1.png)

Seems like this is an IOError in GenTrafficScapy.py, so I add traceback func in that part of code and get this 
![image](https://user-images.githubusercontent.com/34417280/96362316-fcc06f80-115e-11eb-9ae2-c8b0b3495150.png)

Looks like it try to open a temp file, but turns out some wrong happened, I think it is caused by DESTINATION variable received wrong value?
https://github.com/NUS-SNL/p4-traffictool/blob/b0c0ce25a0b1e0f6157ce9dcd9a02c883a936311/p4-traffictool.sh#L214-L218
 https://github.com/NUS-SNL/p4-traffictool/blob/b0c0ce25a0b1e0f6157ce9dcd9a02c883a936311/src/GenTrafficScapy.py#L16-L18
https://github.com/NUS-SNL/p4-traffictool/blob/b0c0ce25a0b1e0f6157ce9dcd9a02c883a936311/src/GenTrafficScapy.py#L588

![image](https://user-images.githubusercontent.com/34417280/96365302-39e22d00-1172-11eb-8dbb-0019de2fc100.png)

**Comment by rhl-bthr** [comment]
Hi @Xiangpeng-Sun. Thanks for reporting the issue.

Looks like you're using a 'different p4c' which does not generate the bmv2 json file as required by p4-traffictool
